//! High-level deno_bindgen bindings for EventBus.
//!
//! These complement the low-level C ABI in `ffi.rs` by providing ergonomic
//! TypeScript bindings auto-generated by deno_bindgen. Uses a global handle
//! registry since deno_bindgen structs must be Serialize/Deserialize.

use deno_bindgen::deno_bindgen;
use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock};

use crate::bus::EventBus;
use crate::events::{Event, EventType};

type HandleMap = HashMap<u32, Arc<EventBus>>;

static HANDLES: OnceLock<Mutex<HandleMap>> = OnceLock::new();
static NEXT_ID: OnceLock<Mutex<u32>> = OnceLock::new();

fn handles() -> &'static Mutex<HandleMap> {
    HANDLES.get_or_init(|| Mutex::new(HashMap::new()))
}

fn next_id() -> u32 {
    let mut id = NEXT_ID.get_or_init(|| Mutex::new(1)).lock().unwrap_or_else(|e| e.into_inner());
    let val = *id;
    match val.checked_add(1) {
        Some(next) => { *id = next; val }
        None => {
            tracing::error!("bindgen handle ID counter overflow");
            0
        }
    }
}

/// Create a new EventBus. Returns a handle ID.
#[deno_bindgen]
fn event_bus_bindgen_create() -> u32 {
    let id = next_id();
    if id == 0 {
        return 0; // overflow sentinel — caller must treat 0 as invalid
    }
    let bus = Arc::new(EventBus::new());
    handles().lock().unwrap_or_else(|e| e.into_inner()).insert(id, bus);
    id
}

/// Publish an event. Returns true on success.
#[deno_bindgen]
fn event_bus_bindgen_publish(handle_id: u32, event_type: u32, payload_json: &str) -> u8 {
    let bus = {
        let map = handles().lock().unwrap_or_else(|e| e.into_inner());
        match map.get(&handle_id) {
            Some(b) => Arc::clone(b),
            None => return 0,
        }
    }; // lock dropped here
    let et = match EventType::from_u32(event_type) {
        Ok(et) => et,
        Err(_) => return 0,
    };
    let payload = payload_json.as_bytes().to_vec();
    let event = Event::new(et, payload);
    bus.publish(event);
    1
}

/// Get subscriber count for an event type.
#[deno_bindgen]
fn event_bus_bindgen_subscriber_count(handle_id: u32, event_type: u32) -> u32 {
    let map = handles().lock().unwrap_or_else(|e| e.into_inner());
    let bus = match map.get(&handle_id) {
        Some(b) => b,
        None => return 0,
    };
    let et = match EventType::from_u32(event_type) {
        Ok(et) => et,
        Err(_) => return 0,
    };
    bus.subscriber_count(et) as u32
}

/// Destroy an EventBus handle.
#[deno_bindgen]
fn event_bus_bindgen_destroy(handle_id: u32) {
    handles().lock().unwrap_or_else(|e| e.into_inner()).remove(&handle_id);
}
